/**
 * API Client - Auto-generated by Orval
 * 
 * This file exports the generated API client functions and types.
 * To regenerate after OpenAPI spec changes, run: npm run generate:api
 */

// Export the generated API functions
export { getAttendees } from './generated/attendees/attendees';

// Export all generated types
export type {
  Attendee,
  AttendeeRegistrationRequest,
  AttendeeResponse,
  AttendeeUpdateRequest,
  ErrorResponse,
  QRCodeResponse,
} from './generated/models';

// Export the axios instance for direct access if needed
export { AXIOS_INSTANCE } from './api-mutator';

/**
 * Attendee API - Convenience wrapper
 * 
 * Usage:
 * ```typescript
 * import { attendeeApi } from '@/lib/api';
 * 
 * // Get attendee by mobile
 * const attendee = await attendeeApi.getByMobile('1234567890');
 * 
 * // Register new attendee
 * const newAttendee = await attendeeApi.register({
 *   mobile: '1234567890',
 *   name: 'John Doe',
 *   email: 'john@example.com'
 * });
 * ```
 */
export const attendeeApi = (() => {
  const api = getAttendees();
  
  return {
    /**
     * Get attendee by mobile number
     * Throws error if not found (404)
     */
    getByMobile: async (mobile: string) => {
      const response = await api.getAttendeeByMobile(mobile);
      if (response.success && response.data) {
        return response.data;
      }
      throw new Error(response.message || 'Failed to fetch attendee');
    },

    /**
     * Register a new attendee
     */
    register: async (data: AttendeeRegistrationRequest) => {
      const response = await api.registerAttendee(data);
      if (response.success && response.data) {
        return response.data;
      }
      throw new Error(response.message || 'Failed to register attendee');
    },

    /**
     * Update attendee details
     */
    update: async (id: string, data: AttendeeUpdateRequest) => {
      const response = await api.updateAttendee(id, data);
      if (response.success && response.data) {
        return response.data;
      }
      throw new Error(response.message || 'Failed to update attendee');
    },

    /**
     * Get attendee by ID
     */
    getById: async (id: string) => {
      const response = await api.getAttendeeById(id);
      if (response.success && response.data) {
        return response.data;
      }
      throw new Error(response.message || 'Failed to fetch attendee');
    },

    /**
     * Generate QR code for attendee
     */
    generateQRCode: async (attendeeId: string) => {
      const response = await api.generateQRCode(attendeeId);
      if (response.success) {
        return response.qrCode;
      }
      throw new Error('Failed to generate QR code');
    },
  };
})();

